# Generated by Django 3.1.4 on 2021-01-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb', '0004_auto_20210120_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitem',
            name='active',
        ),
        migrations.AlterField(
            model_name='coors',
            name='image',
            field=models.ImageField(blank=True, upload_to='course'),
        ),
    ]
