# Generated by Django 3.1.4 on 2021-01-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veb', '0005_auto_20210123_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descriptions',
        ),
    ]
