# Generated by Django 3.1.4 on 2021-01-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb', '0006_remove_category_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tematicblock',
            name='image',
        ),
        migrations.AddField(
            model_name='coors',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coors',
            name='sertification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='href',
            field=models.TextField(blank=True),
        ),
    ]
