# Generated by Django 3.1.4 on 2021-01-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veb', '0008_auto_20210125_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coors',
            name='descriptions',
        ),
    ]
